seq_sunburst:
  jshead: [js/jquery-1.8.2.min.js, js/d3.v3.min.js, js/seq_sunburst.js,  js/colorbrewer.v1.min.js, js/lodash.js]
  css: [css/style.css]
  cdn:
    jshead: 
      - "http://ajax.googleapis.com/ajax/libs/jquery/1.8.2/jquery.min.js"
      - "http://cdnjs.cloudflare.com/ajax/libs/lodash.js/2.4.1/lodash.min.js"
      - "http://d3js.org/d3.v3.min.js"
      - "http://mostlyconjecture.com/rcharts_plugins/seq_sunburst/js/sequence_sunburst.js" 
      - "http://d3js.org/colorbrewer.v1.min.js"
    css: http://mostlyconjecture.com/rcharts_plugins/sequence_sunburst/css/style.css 
