hive_plot:
  jshead: [js/jquery-1.8.2.min.js, js/d3.v3.min.js, js/hive.js]
  css: [css/style.css]
  cdn:
    jshead: 
      - "http://ajax.googleapis.com/ajax/libs/jquery/1.8.2/jquery.min.js"
      - "http://d3js.org/d3.v3.min.js"
      - "http://mostlyconjecture.com/rcharts_plugins/hive_plot/js/hive.js"
    css: http://mostlyconjecture.com/rcharts_plugins/hive_plot/css/style.css
