chord_diagram:
  jshead: [js/jquery-1.8.2.min.js, js/d3.v3.min.js, js/chorddiagram.js]
  css: [css/style.css]
  cdn:
    jshead: 
      - "http://ajax.googleapis.com/ajax/libs/jquery/1.8.2/jquery.min.js"
      - "http://d3js.org/d3.v3.min.js
      - "http://mostlyconjecture.com/rcharts_plugins/chord_diagram/js/d3.chorddiagram.js"
    css: http://mostlyconjecture.com/rcharts_plugins/chord_diagram/css/style.css


