horizon:
  jshead: [js/jquery-1.8.2.min.js, js/lodash.js, js/d3.v3.min.js, js/cubism.v1.min.js, js/horizon.js, js/missing-data.js]
  css: [css/style.css]
  cdn:
    jshead: 
      - "http://ajax.googleapis.com/ajax/libs/jquery/1.8.2/jquery.min.js"
      - "http://d3js.org/d3.v3.min.js"
      - "http://netdna.bootstrapcdn.com/bootstrap/3.1.1/js/bootstrap.min.js"
      - "http://mostlyconjecture.com/rcharts_plugins/horizon_compare/js/cubism.v1.min.js"
      - "http://cdnjs.cloudflare.com/ajax/libs/lodash.js/2.4.1/lodash.min.js"
      - "http://mostlyconjecture.com/rcharts_plugins/horizon_compare/js/horizon.js"
      - "http://mostlyconjecture.com/rcharts_plugins/horizon_compare/js/missing-data.js"
    css: 
      - "http://mostlyconjecture.com/rcharts_plugins/horizon/css/style.css"



