ParallelSets:
  jshead: [js/d3.v3.min.js, js/d3.parsets.js,
  js/jquery-1.8.2.min.js]
  css: [css/d3.parsets.css]
  cdn:
    jshead: 
      - "http://ajax.googleapis.com/ajax/libs/jquery/1.8.2/jquery.min.js"
      - "http://d3js.org/d3.v3.min.js"
      - "http://http://mostlyconjecture.com/rcharts_plugins/parallelsets/js/d3.parsets.js"
    css: http://http://mostlyconjecture.com/rcharts_plugins/parallelsets/css/d3.parsets.css

