ParallelSets:
  jshead: [js/d3.v3.min.js, js/d3.parsets.js,
  js/jquery-1.8.2.min.js]
  css: [css/d3.parsets.css]
  cdn:
    jshead: 
      - "http://ajax.googleapis.com/ajax/libs/jquery/1.8.2/jquery.min.js"
      - "http://wpblog-env.elasticbeanstalk.com/rCharts_plugins/ParallelSets/js/d3.v3.min.js"
      - "http://wpblog-env.elasticbeanstalk.com/rCharts_plugins/ParallelSets/js/d3.parsets.js"
    css: http://wpblog-env.elasticbeanstalk.com/rCharts_plugins/ParallelSets/css/d3.parsets.css

