scatter_matrix:
  jshead: [d3-parsets/d3.v3.min.js, d3-parsets/d3.parsets.js,
  d3-parsets/jquery-1.8.2.min.js]
  css: [d3-parsets/d3.parsets.css]
  cdn:
    jshead: 
      - "http://ajax.googleapis.com/ajax/libs/jquery/1.8.2/jquery.min.js"

